apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minimal-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
    - host: ingress.pembelajaran.my.id
      http:
        paths:
          - backend:
              service:
                name: blog-app
                port:
                  number: 80
            pathType: Prefix
            path: /
