apiVersion: apps/v1
kind: Deployment
metadata:
  name: tool-deployment
spec:
  selector:
    matchLabels:
      app: tool-deployment
  template:
    metadata:
      labels:
        app: tool-deployment
    spec:
      containers:
        - name: tool-deployment
          image: nginx:latest
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 80
          envFrom:
            - secretRef:
                name: tool-secret
