apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-{{ .Values.DEPLOYMENT_NAME }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.DEPLOYMENT_NAME }}
  minReplicas: {{ .Values.MIN_Replicas }}
  maxReplicas: {{ .Values.MAX_Replicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60