apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minimal-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
    - host: ceko.perez
      http:
        paths:
          - backend:
              service:
                name: blog-svc
                port:
                  number: 80
            pathType: Prefix
            path: /
    - host: ingress.pembelajaran.my.id
      http:
        paths:
          - backend:
              service:
                name: blog-svc
                port:
                  number: 80
            pathType: Prefix
            path: /

---
apiVersion: v1
kind: Service
metadata:
  name: blog-svc
spec:
  type: ExternalName
  externalName: blog-app.blog.svc
# test-service.namespacename.svc.cluster.local
