apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minimal-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /

spec:
  rules:
    - http:
        paths:
          - path: /app/blog
            pathType: Prefix
            backend:
              service:
                name: blog-svc
                port:
                  number: 80

---
apiVersion: v1
kind: Service
metadata:
  name: blog-svc
spec:
  type: ExternalName
  externalName: blog.svc.blog-app-svc
