apiVersion: apps/v1
kind: Deployment
metadata:
  name: klikgeni-test-deployment
  labels:
    app: klikgeni
spec:
  replicas: 1
  selector:
    matchLabels:
      app: klikgeni-test-deployment
  template:
    metadata:
      labels:
        app: klikgeni-test-deployment
    spec:
      hostNetwork: true
      containers:
        - name: klikgeni-test-deployment
          image: geniwhitelabel/backend-service:klikgeni_web_test
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: klikgeni-test-configmap-deployment
          env:
            - name: DB_DATABASE
              value: klikgeni_test
            - name: DB_HOST
              value: 103.82.243.89
            - name: DB_USERNAME
              value: klikgeni-test
            - name: DB_PASSWORD
              value: Eshaezaedoo6zae
            - name: DB_PORT
              value: "3307"
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          # livenessProbe:
          #   initialDelaySeconds: 5
          #   periodSeconds: 60
          #   timeoutSeconds: 60
          #   successThreshold: 1
          #   failureThreshold: 3
          #   httpGet:
          #     scheme: HTTP
          #     path: /
          #     port: 80
          resources:
            requests:
              memory: "125Mi"
              cpu: "500m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          # args:
          #   - "--kubelet-insecure-tls"
          #   - "--kubelet-preferred-address-types=InternalIP,ExternalIP"
          ports:
            - containerPort: 80
          # volumeMounts:
          #   - mountPath: /var/www/html/public/image
          #     name: laravel-public
          #     subPath: klikgeni-test/public
      # volumes:
      #   - name: laravel-public
      #     persistentVolumeClaim:
      #       claimName: klikgeni-test-public
