apiVersion: v1
kind: Secret
metadata:
  name: klikgeni-prod-secret
data:
  default_username: ENC[AES256_GCM,data:Z95nllLFGhJCiserWG+AfgkNrkFvAHfu,iv:DYsoC3mJRvpYZDMUKqwA/4JWQhi4wp10SETDoVeAe/8=,tag:2yF1+PhJDh2AAnHjMyEVWw==,type:str]
  default_password: ENC[AES256_GCM,data:8jHVGVPRySp8LK5h8IMNcsfMWNoudGpP72wdv3KaY5X6lrXi,iv:C2bykEBXoDhf6aYUSP/qQLAZ2QukBKUGhMWTXydm2Qs=,tag:BklOfNRZRJSllthAEjnmcA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1hda7kp0t5q27257thpsl87q3n2tmf4w5rz2xn7ew2j963zxmqfks8xaah7
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKLzdxeC9IUXVkeTNZTzFv
        TW1Yc3dwQ0Y2Ujk5WmR3QVpSUkFJT2RDMm1FCjF6VlRRZWpBVUcrOC8yM0JocDJN
        OVVRNkFxK1J2ZkdZTnR4MFhxMElwVmsKLS0tICt0cStMcFZ2ZGsxbVRPMWJ2ckpD
        b0t0cWgrazVheDFYdmFKOEtCTjRtOGcK5Lzr8vgaXxUjLjmygoU4bSmhQErqlwBz
        /+p7BmsEDkxLW31HLuWXW+HLjiSkGpnf4WMnErfN01gm3yCj9eOBJw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2023-02-02T07:00:07Z"
  mac: ENC[AES256_GCM,data:imrsiVshGLUDjXF1HYKcrJKXNZI0XIHwxXW/bmw8ck7XKFDKt7aDwOI93ITvMaswE0W94GF7F46nx/G1PJo8vW0AbndQikoiEoEp5Aiik0v3iMJK3ZFrMt3Kr/L0t6UZAzOuon1AAKvm11R4M7hwx3qoOyx0eJu4JoTMEdQVBkE=,iv:sLJoDwHT95Ss7kkNAY1z31XGzYbmY7D32Mq9s85BT+Y=,tag:sI6VaW1vRtEoWo4aMHrrfw==,type:str]
  pgp: []
  encrypted_regex: ^(data)$
  version: 3.7.3
